<?php

namespace SchoolBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new \SchoolBundle\Entity\Book;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new \SchoolBundle\Entity\Book : $obj;
        }
    }
}
