<?php

namespace SchoolBundle\Repository;

/**
 * BookBorrowingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookBorrowingRepository extends \Doctrine\ORM\EntityRepository
{
}
