<?php

namespace SchoolBundle\Repository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new \SchoolBundle\Entity\Exam;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new \SchoolBundle\Entity\Exam : $obj;
        }
    }
}
