<?php

namespace SchoolBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new \SchoolBundle\Entity\Student;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new \SchoolBundle\Entity\Student : $obj;
        }
    }
}
