core_dossier_home:
    path:     /
    defaults: { _controller: CoreBundle:Dossier:index }

core_dossier_insert:
    path:     /insert
    defaults: { _controller: CoreBundle:Dossier:insert }

core_dossier_update:
    path:     /update/{id}
    defaults: { _controller: CoreBundle:Dossier:insert }

core_dossier_delete:
    path:     /delete/{id}
    defaults: { _controller: CoreBundle:Dossier:delete }

core_dossier_archives:
    path:     /archives
    defaults: { _controller: CoreBundle:Dossier:archives }

core_dossier_archive:
    path:     /archive/{id}
    defaults: { _controller: CoreBundle:Dossier:archive }

core_dossier_one:
    path:   /{id}
    defaults: { _controller: CoreBundle:Dossier:one }
