# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
       #  in_memory:
         #    memory: ~
        user_db:
            entity: { class: CoreBundle\Entity\User, property: email }
        in_memory:
            memory:
                users:
                    mcssym:
                        #oms@2016
                        password: $2y$12$tq8Y8jmKwPLKMw6OcGLmTeHMZrl1Zrv.qxhuiBYpOHQi42kCHON9W
                        roles: 'ROLE_SUPER_ADMIN'
                    admin:
                        password: $2y$12$tq8Y8jmKwPLKMw6OcGLmTeHMZrl1Zrv.qxhuiBYpOHQi42kCHON9W
                        roles: 'ROLE_ADMIN'
        
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_EMPLOYEE:     [ROLE_USER]
        ROLE_ADMIN:       [ROLE_EMPLOYEE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate


            form_login:
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                login_path: core_login
                check_path: core_check
                success_handler: authentication_handler

            logout:
                path: /logout
                target: /
                handlers: [logout_handler]
            
            remember_me:
                secret: "%secret%"
                lifetime: 2232000
                path: /
                remember_me_parameter: "_remember_me"
                always_remember_me: false

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }