<?php

namespace MarketBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new \MarketBundle\Entity\Commande;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new \MarketBundle\Entity\Commande : $obj;
        }
    }
}
