<?php

namespace MarketBundle\Repository;

/**
 * ProductVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVariantRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new \MarketBundle\Entity\ProductVariant;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new \MarketBundle\Entity\ProductVariant : $obj;
        }
    }
}
