<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Competence;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new Competence;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new Competence : $obj;
        }
    }
}
