<?php

namespace CoreBundle\Repository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($query, $limit = null, $order = null) {
        $qb = $this->createQueryBuilder('a');
        $qb->where($qb->expr()->like('a.name', ':n'))
            ->setParameter('n','%'.$query.'%');
        $qb->andWhere($qb->expr()->eq('a.archive', ':r'))
            ->setParameter('r',false);
        $qb->orWhere($qb->expr()->like('a.numero', ':m'))
            ->setParameter('m','%'.$query.'%');
        $qb->orderBy('a.id', 'DESC')
			->setMaxResults($limit)
			->setFirstResult($order);

        return $qb->getQuery()->getResult();
    }
}
