<?php

namespace CoreBundle\Repository;

/**
 * PenaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
