<?php

namespace CoreBundle\Repository;


use CoreBundle\Entity\Poste;

/**
 * PosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteRepository extends \Doctrine\ORM\EntityRepository
{
    public function oneOrNew($id = null) {
        if($id == null) {
            return new Poste;
        }else{
            $obj = $this->findOneById($id);
            return empty($obj) ? new Poste : $obj;
        }
    }
}
