<?php

namespace CoreBundle\Repository;

/**
 * SalaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaireRepository extends \Doctrine\ORM\EntityRepository
{
}
