<?php

namespace CoreBundle\Repository;

/**
 * UserEchelonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEchelonRepository extends \Doctrine\ORM\EntityRepository
{
}
