<?php

namespace CMBundle\Repository;

/**
 * BorrowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowerRepository extends \Doctrine\ORM\EntityRepository
{
}
