core_carriere_home:
    path:     /
    defaults: { _controller: CoreBundle:Carriere:index }

core_carriere_insert:
    path:     /insert
    defaults: { _controller: CoreBundle:Carriere:insert }

core_carriere_update:
    path:     /update/{id}
    defaults: { _controller: CoreBundle:Carriere:insert }

core_carriere_active:
    path:     /activev/{id}
    defaults: { _controller: CoreBundle:Carriere:active }

core_carriere_delete:
    path:     /delete/{id}
    defaults: { _controller: CoreBundle:Carriere:delete }

core_carriere_archives:
    path:     /archives
    defaults: { _controller: CoreBundle:Carriere:archives }

core_carriere_archive:
    path:     /archive/{id}
    defaults: { _controller: CoreBundle:Carriere:archive }

core_carriere_one:
    path:   /{id}
    defaults: { _controller: CoreBundle:Carriere:one }
